### ISSUE TITLE
cannot use CSS variables

### ISSUE THREAD

**Issue by aweary** [tailwindlabs/tailwindcss-jit#102]
### What version of @tailwindcss/jit are you using?

0.1.3

### What version of Node.js are you using?

12.20.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://www.youtube.com/watch?v=4e7iksx-Zig

I'd expect that:
```jsx
<div className="p-[var(--app-padding)]" />
```
would generate something like
```css
.p-[var(--app-padding)] {
  padding: var(--app-padding);
}
```
but seems like it just does nothing
