### ISSUE TITLE
@apply sm: is not generated with npm run hot/watch

### ISSUE THREAD

**Issue by Livijn** [tailwindlabs/tailwindcss-jit#132]
### What version of @tailwindcss/jit are you using?

0.1.4

### What version of Node.js are you using?

15.11.0

### What browser are you using?

Chome

### What operating system are you using?

macOS

### Reproduction repository

lul

I am missing classes when using sm modifiers together with `@apply`. The media query seems to be generated but without any content. This does not happen when running `npm run prod`. I am just using `mix.sass('resources/sass/app.scss', 'public/css')`.

SCSS:
```css
@layer components {
  .btn-green, .btn-indigo, .btn-red, .btn-orange, .btn-white, .btn-gray {
    @apply border font-bold rounded-md py-2 px-3 sm:py-3 sm:px-4 focus:ring-2;

    &:disabled {
      @apply opacity-50 cursor-not-allowed;
    }
  }
}
```

CSS:
```css
.btn-green, .btn-indigo, .btn-red, .btn-orange, .btn-white, .btn-gray{
	border-radius: 0.375rem;
	border-width: 1px;
	padding-left: 0.75rem;
	padding-right: 0.75rem;
	padding-top: 0.5rem;
	padding-bottom: 0.5rem;
	font-weight: 700;
}
@media (min-width: 640px){}
.btn-green:disabled, .btn-indigo:disabled, .btn-red:disabled, .btn-orange:disabled, .btn-white:disabled, .btn-gray:disabled{
	cursor: not-allowed;
	opacity: 0.5;
}
```

tailwind.config.js
```js
module.exports = {
  purge: {
    content: [
      './resources/js/**/*.vue',
      './resources/sass/*.scss',
      './resources/views/**/*.blade.php',
    ],
    options: {
      safelist: [/md:grid-cols-\d+/, /lg:grid-cols-\d+/]
    }
  },
  // etc
}
```
