### ISSUE TITLE
JIT compilation doesn't remove unused classes when the DOM changes

### ISSUE THREAD

**Issue by michaeldyrynda** [tailwindlabs/tailwindcss-jit#57]
If I was to write the following snippet with the (Laravel Mix) JIT-compiler watching:

```html
<div class="relative max-w-md bg-white rounded shadow"></div>
```

Then decide I want to have `shadow-md` instead:

```diff
- <div class="relative max-w-md bg-white rounded shadow"></div>
+ <div class="relative max-w-md bg-white rounded shadow-md"></div>
```

The compiled stylesheet will have both `.shadow` and `.shadow-md` in it.

```css
.shadow {
        --tw-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
        box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}
.shadow-md {
        --tw-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
        box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}
```

If I restart the watcher, `.shadow` is dropped from the compiled stylesheet.
