### ISSUE TITLE
Support for recursive `@apply`

### ISSUE THREAD

**Issue by rolandleth** [tailwindlabs/tailwindcss-jit#66]
All of these work with `tailwindcss`, but with `@tailwindcss/jit` they don't, no matter the order of `bg-white` and `some-class`:

```css
@layer components {
    .some-class {
        @apply bg-red-500;
    }

    .some-other-class {
        @apply bg-white some-class;
    }
}
```

```css
@layer components {
    .some-class {
        @apply bg-red-500;
    }

    .some-other-class {
        @apply bg-white;
        @apply some-class;
    }
}
/* this one even removes everything from `.some-other-class` */
```

```css
@layer components {
    .some-class {
        background-color: red;
    }

    .some-other-class {
        @apply bg-white some-class;
    }
}
```

It looks like `--tw` variables aren't overwritten; in these examples, `background-color` is always `rgba(255, 255, 255, var(--tw-bg-opacity))`.

This is the only I saw it works, but it's weird and the only reason it's working is that the explicit `background-color` replaces the one set via `@apply` (final value is `red`, so it doesn't go through TW):

```css
@layer components {
    .some-class {
        background-color: red;
    }

    .some-other-class {
        @apply bg-white;
        @apply some-class; /* reversing them doesn't work */
    }
}
```
