### ISSUE TITLE
Keyframes malformed when using animation utilities with `@apply`

### ISSUE THREAD

**Issue by adamwathan** [tailwindlabs/tailwindcss-jit#94]
When you use `@apply` with any of the animation utilities, the keyframe children are missing their selectors:

```css
/* Input */
@tailwind utilities;

@layer utilities {
  .foo {
    @apply animate-spin;
  }
}

/* Output */
.foo {
  animation: spin 1s linear infinite
}

@keyframes spin {
   {
    transform: rotate(360deg)
  }
}
```

The actual `@keyframes` rule is generated later in the output than I would expect as well — I'd think it would come first.
